#pragma once

// Driver name and device name
#define DRIVER_NAME L"CeasefireDriver"
#define DEVICE_NAME L"\\Device\\CeasefireDriver"
#define DOS_DEVICE_NAME L"\\DosDevices\\CeasefireDriver"

// IOCTL control codes
#define IOCTL_ADD_RULE      CTL_CODE(FILE_DEVICE_NETWORK, 0x801, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_REMOVE_RULE   CTL_CODE(FILE_DEVICE_NETWORK, 0x802, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_UPDATE_RULE   CTL_CODE(FILE_DEVICE_NETWORK, 0x803, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_CLEAR_RULES   CTL_CODE(FILE_DEVICE_NETWORK, 0x804, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_GET_EVENT     CTL_CODE(FILE_DEVICE_NETWORK, 0x805, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_GET_DNS_EVENT CTL_CODE(FILE_DEVICE_NETWORK, 0x806, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_SET_DEFAULT_POLICY CTL_CODE(FILE_DEVICE_NETWORK, 0x807, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_SET_THROTTLE  CTL_CODE(FILE_DEVICE_NETWORK, 0x808, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_GET_DIAGS     CTL_CODE(FILE_DEVICE_NETWORK, 0x809, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_CLEAR_THROTTLE CTL_CODE(FILE_DEVICE_NETWORK, 0x80A, METHOD_BUFFERED, FILE_ANY_ACCESS)

// Protocol types
#define PROTOCOL_TCP 6
#define PROTOCOL_UDP 17
#define PROTOCOL_ANY 0

// Rule action
#define RULE_ACTION_ALLOW 1
#define RULE_ACTION_BLOCK 0

// Maximum values
#define MAX_PATH_LENGTH 260
#define MAX_RULES 1000
#define EVENT_QUEUE_SIZE 1000
